/rm_fire_control:
  ros__parameters:
    large_armor_width: 0.23  
    large_armor_height: 0.127
    small_armor_width: 0.135
    small_armor_height: 0.125
    k: 0.038  
    gravity: 9.79
    s_bias: 
    z_bias:
    yaw_motor_res_speed: 1.6
    tranfer_thresh: 5